# Generated by Django 4.1.7 on 2023-04-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='order',
            new_name='cart',
        ),
    ]
